-- Create tables
CREATE TABLE sales (
    id SERIAL PRIMARY KEY,
    BOED_ID TEXT,
    Trade_Date DATE,
    Trade_ID INT,
    Execution_Date DATE,
    Execution_Time TIME,
    Execution_ID INT,
    REF TEXT,
    Country TEXT,
    Client TEXT,
    Trader TEXT,
    Buy_Sell TEXT,
    Term DATE,
    Start_Date DATE,
    End_Date DATE,
    Expiry DATE,
    Strike FLOAT,
    TotalQty INT,
    Trade_Unit TEXT,
    Total_Amount INT,
    Base_Unit TEXT,
    Period TEXT,
    Price FLOAT,
    Exchange TEXT,
    Asset TEXT,
    Product TEXT,
    Instrument_Group TEXT,
    Market TEXT,
    Instrument TEXT,
    Product_ID TEXT,
    Strategy TEXT,
    Type TEXT,
    Type_2 TEXT,
    Clearing_account TEXT,
    Bro_rate FLOAT,
    Commission FLOAT,
    Broker TEXT,
    POS_Date DATE
);


